[package]
name = "confy"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = "4.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
merge-struct = "0.1"
jsonschema = "0.16"
similar = "2.2"
